config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flights
  resources :bookings
  # Defines the root path route ("/")
  # root "articles#index"
  root 'flights#index'
end

app/models/airport.rb
# frozen_string_literal: true

class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: :departure_airport
  has_many :arriving_flights, class_name: 'Flight', foreign_key: :arrival_airport
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, inverse_of: :booking
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
# frozen_string_literal: true

class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: :departure_airport
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: :arrival_airport
  has_many :flight_passengers
  has_many :passengers, through: :flight_passengers
  has_many :bookings
end

app/models/flight_passenger.rb
class FlightPassenger < ApplicationRecord
  belongs_to :flight
  belongs_to :passenger
end

app/models/passenger.rb
# frozen_string_literal: true

class Passenger < ApplicationRecord
  has_many :flight_passengers
  has_many :flights, through: :flight_passengers
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @flight = Flight.find(params[:flight_id])
    @passengers_count = params[:passenger_count].to_i
    @booking = Booking.new
    @passengers_count.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.flight_id = params[:flight_id]

    if @booking.save
      flash[:notice] = 'Booking created successfuly!'
      redirect_to @booking
    else
      flash[:warning] = 'Something went wrong'
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])

    if @booking.destroy
      flash[:notice] = 'Booking deleted!'
    else
      flash[:warning] = 'Something went wrong'
    end
    redirect_to booking_path
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: %i[id name email _destroy])
  end
end

app/controllers/flights_controller.rb
# frozen_string_literal: true

class FlightsController < ApplicationController
  def index
    @departure_airport = params[:departure_airport]
    @arrival_airport = params[:arrival_airport]

    @search = Flight.all.where(departure_airport: @departure_airport, arrival_airport: @arrival_airport)
  end
end

app/controllers/passengers_controller.rb
# frozen_string_literal: true

class PassengersController < ApplicationController
  def new
    @passenger = Passenger.new
  end

  def create
    @passenger = Passenger.new(passenger_params)

    if @passenger.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def passenger_params
    params.require(:passenger).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/index.html.erb
<% @bookings.each do |b| %>
  <h2><%= link_to "Booking ##{b.id}", b %></h2>
<% end %>

app/views/bookings/new.html.erb
<h2>Flight Info:</h2>
Departure Airport: <%= @flight.departure_airport.code %><br>
Arrival Airport: <%= @flight.arrival_airport.code %><br>
Flight Date: <%= @flight.departure_time.strftime('%Y-%m-%d at %H:%M') %><br>
Flight Duration: <%= @flight.duration %> minutes

<h2>Passenger Info:</h2>
<%= form_for @booking do |f| %>
  <%= hidden_field_tag(:flight_id, params[:flight_id]) %>
    <%= f.fields_for :passengers do |p| %>
      <%= p.label :name %>
      <p><%= p.text_field :name, required: true %></p>
      <%= p.label :email %>
      <p><%= p.email_field :email, required: true %></p><br><br>
      <%= p.hidden_field :id %>
    <% end %>
  <%= submit_tag %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking number #<%= @booking.id %>:</h1>
<% @booking.passengers.each_with_index do |p, i| %>
  <h3>Passenger <%= i + 1 %>:</h3>
  <p>Name: <%= p.name %></p>
  <p>Email: <%= p.email %></p>
<% end %>

app/views/flights/index.html.erb
<h1>Flight Search</h1>

<%= form_tag flights_path, method: :get do %>
  <div>
    <label for="departure_airport">Departure Airport:</label>
    <%= select_tag 'departure_airport', options_for_select(Airport.all.map { |a| [a.code, a.id] }), prompt: 'Select Departure Airport', required: true %>
  </div>

  <div>
    <label for="arrival_airport">Arrival Airport:</label>
    <%= select_tag 'arrival_airport', options_for_select(Airport.all.map { |a| [a.code, a.id] }), prompt: 'Select Arrival Airport', required: true %>
  </div>

  <div>
    <label for="passenger_count">Number of Passengers:</label>
    <%= select_tag 'passenger_count', options_for_select((1..4).to_a.map { |n| [n, n] }), prompt: 'Select Number of Passengers', required: true %>
  </div>

  <div>
    <label for="flight_date">Flight Date:</label>
    <%= select_tag 'flight_date', options_for_select(Flight.all.map { |d| [d.departure_time.strftime('%Y-%m-%d'), d.departure_time.strftime('%Y-%m-%d')] }), prompt: 'Select Flight Date', required: true %>
  </div>

  <%= submit_tag 'Search' %>
<% end %>

<% if params[:commit] %>
  <% if @search.nil? || @search.empty? %>
    No flights found
  <% else %>
    <%= form_tag new_booking_path, method: :get do %>
      <% @search.each do |s| %>
        <%= radio_button_tag(:flight_id, s.id) %>
        <%= label_tag(:flight_id, s.departure_time) %><br>
      <% end %>
    <%= hidden_field_tag(:passenger_count, params[:passenger_count]) %>
    <%= submit_tag 'Submit' %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>